name: Pull request workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repo
        uses: actions/checkout@v2
      - name: Récupération de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Execution des tests
        run: mvn test
    build-app:
      runs-on: ubuntu-latest
      steps:
        - name: Récupération du repo
          uses: actions/checkout@v2
        - name: Récupération de java
          uses: actions/setup-java@v2
          with:
            distribution: adopt
            java-version: 11
        - name: créations du jar
          run: mvn package
        - name: Upload du jar
          uses: actions/upload-artifact@v2
          with:
              name: app.jar
              path: ./target/testDemo-0.0.1-SNAPSHOT.jar
    build-docker:
     needs: build-app
     runs-on: ubuntu-latest
     steps:
       - name:  Récuperation du jar
         uses: actions/dowload-artifact@v2
         with:
           name: app.jar
        -run: ls


